spring.application.name=api
spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.mrdwosqqsqdczmngzhlx
spring.datasource.password=1WQcXHToQS9FAPwF
spring.datasource.driver-class-name=org.postgresql.Driver

